# Generated by Django 4.0.3 on 2022-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_mps',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
